### ISSUE TITLE
Error starting node

### ISSUE THREAD

**Issue by husimo** [dariusk/rss-to-activitypub#21]
Hello, running "node index.js" I have the following error : 

```
module.js:550
    throw err;
    ^

Error: Cannot find module './message'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/routes/index.js:6:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

Thank you :-)

**Comment by dariusk** [comment]
Thanks for the report. What version of node are you running?

**Comment by husimo** [comment]
Tested with v11.13.0 and v10.15.3, same error. Thank you :-) 

Could not it be related to the fact there is no `message.js` in ``routes` directory ?

**Comment by dariusk** [comment]
Oh wow, yes, I forgot to add a file to the git repo! I'll fix this soon.
thanks.

**Comment by husimo** [comment]
Thank you, I look forward to it :-)

**Comment by dariusk** [comment]
This should be fixed! Sorry for the delay.
