### ISSUE TITLE
Add generate-rsa-keypair in dependancies.

### ISSUE THREAD

**Issue by AntoineVe** [dariusk/rss-to-activitypub#30]
generate-rsa-keypair is not installed npm i

resulting in

node index.js

internal/modules/cjs/loader.js:657
    throw err;          
    ^           
                                                               
Error: Cannot find module './build/Release/generate-rsa-keypair.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)                                                                                                            
    at require (internal/modules/cjs/helpers.js:14:16)                                                                                                                   
    at Object.<anonymous> (/usr/home/RSS/rss-to-activitypub/node_modules/generate-rsa-keypair/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)

**Comment by dariusk** [comment]
This is already in the `package.json` -- it might be an issue with your local environment. There are some possible solutions listed here:

https://stackoverflow.com/questions/9023672/how-do-i-resolve-cannot-find-module-error-using-node-js

**Comment by hieronymousch** [comment]
Tried to install on two seperate systems, both fail for the RSA module. They run other node stuff without issues. Any idea how to solve this?
